language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-26
    - build-tools-26.0.1
    - extra-android-m2repository

notifications:
  email:
      on_failure: change

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check
  - ./gradlew build
