language: android

android:
  components:
    - tools
    - platform-tools
    - android-29
    - build-tools-29.0.2
    - extra-android-m2repository

notifications:
  email:
      on_failure: change

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check
  - ./gradlew build
