language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-26
    - build-tools-26.0.1

notifications:
  email: false

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check
  - ./gradlew build
